In [81]:
import pandas as pd
import numpy as np

In [82]:
df2021 = pd.read_csv('../dados/dados_brutos/datatran2021.csv',sep=';', encoding='latin-1')
df2022 = pd.read_csv('../dados/dados_brutos/datatran2022.csv',sep=';', encoding='latin-1')
df2023 = pd.read_csv('../dados/dados_brutos/datatran2023.csv',sep=';', encoding='latin-1')
df2024 = pd.read_csv('../dados/dados_brutos/datatran2024.csv',sep=';', encoding='latin-1')
df2025 = pd.read_csv('../dados/dados_brutos/datatran2025.csv',sep=';', encoding='latin-1')

df = pd.concat([df2021,df2022, df2023, df2024, df2025],ignore_index=True)
df

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,331730.0,2021-01-01,sexta-feira,05:30:00,SP,116,453,REGISTRO,Reação tardia ou ineficiente do condutor,Tombamento,...,0,0,0,1,1,"-24,56168114","-47,86752174",SPRF-SP,DEL05-SP,UOP01-DEL05-SP
1,331804.0,2021-01-01,sexta-feira,08:05:00,AM,174,937,MANAUS,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,5,1,1,5,"-2,508068","-60,036434",SPRF-AM,DEL01-AM,UOP01-DEL01-AM
2,331815.0,2021-01-01,sexta-feira,10:10:00,CE,222,"128,5",ITAPAJE,Velocidade Incompatível,Tombamento,...,0,0,11,2,12,"-3,707626","-39,623509",SPRF-CE,DEL04-CE,UOP03-DEL04-CE
3,331823.0,2021-01-01,sexta-feira,12:30:00,RJ,493,18,MAGE,Ingestão de álcool e/ou substâncias psicoativa...,Colisão lateral,...,0,1,1,1,3,"-22,6687122","-43,01862696",SPRF-RJ,DEL04-RJ,UOP02-DEL04-RJ
4,331843.0,2021-01-01,sexta-feira,14:40:00,RJ,393,252,BARRA DO PIRAI,Condutor Dormindo,Colisão frontal,...,1,1,1,2,3,"-22,43422023","-43,77561487",SPRF-RJ,DEL05-RJ,UOP04-DEL05-RJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342614,754864.0,2025-12-12,sexta-feira,22:58:00,PB,104,118,LAGOA SECA,Ausência de sinalização,Tombamento,...,0,0,0,1,1,"-7,184132","-35,865765",SPRF-PB,DEL02-PB,UOP04-DEL02-PB
342615,754925.0,2025-10-30,quinta-feira,13:40:00,PA,0,0,ANANINDEUA,Reação tardia ou ineficiente do condutor,Colisão transversal,...,0,0,1,2,3,"-1,377841","-48,4051",SPRF-GO,DEL02-GO,UOP01-DEL02-GO
342616,755021.0,2025-12-31,quarta-feira,21:30:00,ES,259,39,COLATINA,Pedestre andava na pista,Atropelamento de Pedestre,...,0,0,1,0,2,"-19,55231101","-40,56331637",SPRF-ES,DEL02-ES,UOP01-DEL02-ES
342617,755045.0,2025-11-15,sábado,22:50:00,MG,459,93,CONGONHAL,Ausência de reação do condutor,Colisão frontal,...,0,0,0,3,2,"-22,174878","-46,000213",SPRF-MG,DEL09-MG,UOP01-DEL09-MG
342618,755105.0,2025-09-23,terça-feira,01:45:00,MG,262,"48,5",MANHUACU,Velocidade Incompatível,Saída de leito carroçável,...,13,14,0,29,1,"-20,24426377","-42,13615895",SPRF-MG,DEL06-MG,UOP03-DEL06-MG

In [83]:
#As colunas "regional", "delegacia" e "uop" são desnecessárias, então removemos do df

df = df.drop(columns=['regional', 'delegacia', 'uop'])
df.head()

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude
0,331730.0,2021-01-01,sexta-feira,05:30:00,SP,116,453,REGISTRO,Reação tardia ou ineficiente do condutor,Tombamento,...,1,0,1,0,0,0,1,1,"-24,56168114","-47,86752174"
1,331804.0,2021-01-01,sexta-feira,08:05:00,AM,174,937,MANAUS,Reação tardia ou ineficiente do condutor,Colisão traseira,...,7,0,1,0,5,1,1,5,"-2,508068","-60,036434"
2,331815.0,2021-01-01,sexta-feira,10:10:00,CE,222,"128,5",ITAPAJE,Velocidade Incompatível,Tombamento,...,3,0,2,0,0,11,2,12,"-3,707626","-39,623509"
3,331823.0,2021-01-01,sexta-feira,12:30:00,RJ,493,18,MAGE,Ingestão de álcool e/ou substâncias psicoativa...,Colisão lateral,...,3,0,1,0,1,1,1,3,"-22,6687122","-43,01862696"
4,331843.0,2021-01-01,sexta-feira,14:40:00,RJ,393,252,BARRA DO PIRAI,Condutor Dormindo,Colisão frontal,...,4,0,1,1,1,1,2,3,"-22,43422023","-43,77561487"

In [84]:
df.describe()

,id,br,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
count,342619.000000,342619.000000,342619.000000,342619.000000,342619.000000,342619.000000,342619.000000,342619.000000,342619.000000,342619.000000
mean,541128.401061,209.867818,2.573328,0.083673,0.864815,0.277772,1.035471,0.398361,1.142587,1.986521
std,118135.599723,129.784419,2.169098,0.344471,1.076109,0.618761,1.704881,0.849062,1.197769,1.119596
min,331693.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,449100.500000,101.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,544622.000000,158.000000,2.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,2.000000
75%,638771.500000,324.000000,3.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,2.000000
max,755260.000000,498.000000,95.000000,37.000000,83.000000,35.000000,78.000000,88.000000,84.000000,131.000000

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 342619 entries, 0 to 342618
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      342619 non-null  float64
 1   data_inversa            342619 non-null  object
 2   dia_semana              342619 non-null  object
 3   horario                 342619 non-null  object
 4   uf                      342619 non-null  object
 5   br                      342619 non-null  int64
 6   km                      342619 non-null  object
 7   municipio               342619 non-null  object
 8   causa_acidente          342619 non-null  object
 9   tipo_acidente           342619 non-null  object
 10  classificacao_acidente  342614 non-null  object
 11  fase_dia                342619 non-null  object
 12  sentido_via             342619 non-null  object
 13  condicao_metereologica  342619 non-null  object
 14  tipo_pista              342619 non-null  object
 15  tracado_via             342619 non-null  object
 16  uso_solo                342619 non-null  object
 17  pessoas                 342619 non-null  int64
 18  mortos                  342619 non-null  int64
 19  feridos_leves           342619 non-null  int64
 20  feridos_graves          342619 non-null  int64
 21  ilesos                  342619 non-null  int64
 22  ignorados               342619 non-null  int64
 23  feridos                 342619 non-null  int64
 24  veiculos                342619 non-null  int64
 25  latitude                342619 non-null  object
 26  longitude               342619 non-null  object
dtypes: float64(1), int64(9), object(17)
memory usage: 70.6+ MB

In [86]:
df['data_inversa'] = pd.to_datetime(df['data_inversa'])

In [87]:
df.isnull().sum()
#5 valores nulos apenas

id                        0
data_inversa              0
dia_semana                0
horario                   0
uf                        0
br                        0
km                        0
municipio                 0
causa_acidente            0
tipo_acidente             0
classificacao_acidente    5
fase_dia                  0
sentido_via               0
condicao_metereologica    0
tipo_pista                0
tracado_via               0
uso_solo                  0
pessoas                   0
mortos                    0
feridos_leves             0
feridos_graves            0
ilesos                    0
ignorados                 0
feridos                   0
veiculos                  0
latitude                  0
longitude                 0
dtype: int64

In [88]:
df['classificacao_acidente'].value_counts()

classificacao_acidente
Com Vítimas Feridas    260920
Sem Vítimas             57076
Com Vítimas Fatais      24618
Name: count, dtype: int64

In [89]:
#Lidando com os valores nulos na coluna 'classificacao_acidente'
condicoes = [
    df['mortos'] > 0,
    df['feridos'] > 0,
    df['feridos'] == 0
]

classificacao = ['Com Vítimas Fatais', 'Com Vítimas Feridas', 'Sem Vítimas']
df['classificacao_acidente'] = np.select(condicoes, classificacao)

In [90]:
df['classificacao_acidente'].value_counts()

classificacao_acidente
Com Vítimas Feridas    260924
Sem Vítimas             57076
Com Vítimas Fatais      24619
Name: count, dtype: int64

In [91]:
#Criar coluna de feriado

import holidays
feriados_br = holidays.Brazil(years=[2021, 2022, 2023, 2024, 2025])
df['feriado'] = df['data_inversa'].isin(feriados_br)

df.head(15)

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,feriado
0,331730.0,2021-01-01,sexta-feira,05:30:00,SP,116,453,REGISTRO,Reação tardia ou ineficiente do condutor,Tombamento,...,0,1,0,0,0,1,1,"-24,56168114","-47,86752174",True
1,331804.0,2021-01-01,sexta-feira,08:05:00,AM,174,937,MANAUS,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,1,0,5,1,1,5,"-2,508068","-60,036434",True
2,331815.0,2021-01-01,sexta-feira,10:10:00,CE,222,"128,5",ITAPAJE,Velocidade Incompatível,Tombamento,...,0,2,0,0,11,2,12,"-3,707626","-39,623509",True
3,331823.0,2021-01-01,sexta-feira,12:30:00,RJ,493,18,MAGE,Ingestão de álcool e/ou substâncias psicoativa...,Colisão lateral,...,0,1,0,1,1,1,3,"-22,6687122","-43,01862696",True
4,331843.0,2021-01-01,sexta-feira,14:40:00,RJ,393,252,BARRA DO PIRAI,Condutor Dormindo,Colisão frontal,...,0,1,1,1,1,2,3,"-22,43422023","-43,77561487",True
5,331844.0,2021-01-01,sexta-feira,15:20:00,BA,101,"818,1",ITAMARAJU,Velocidade Incompatível,Tombamento,...,0,1,0,0,1,1,2,"-17,16637837","-39,57859039",True
6,331855.0,2021-01-01,sexta-feira,15:45:00,PR,277,"51,3",SAO JOSE DOS PINHAIS,Pista Escorregadia,Saída de leito carroçável,...,0,1,0,3,0,1,3,"-25,59515989","-48,90700787",True
7,331857.0,2021-01-01,sexta-feira,15:30:00,GO,20,183,ALVORADA DO NORTE,Demais falhas mecânicas ou elétricas,Incêndio,...,0,0,0,1,1,0,2,"-14,456929","-46,474163",True
8,331864.0,2021-01-01,sexta-feira,17:10:00,SC,470,"79,1",INDAIAL,Transitar na contramão,Colisão frontal,...,2,5,1,0,1,6,4,"-26,951565","-49,306534",True
9,331871.0,2021-01-01,sexta-feira,16:15:00,MG,381,"6,8",BETIM,Condutor Dormindo,Colisão traseira,...,0,1,1,1,1,2,3,"-19,96825","-44,198708",True
10,331910.0,2021-01-01,sexta-feira,19:50:00,SC,470,130,LONTRAS,Acessar a via sem observar a presença dos outr...,Colisão transversal,...,0,0,2,2,1,2,3,"-27,16037609","-49,55657959",True
11,331920.0,2021-01-01,sexta-feira,20:40:00,PR,116,59,CAMPINA GRANDE DO SUL,Entrada inopinada do pedestre,Atropelamento de Pedestre,...,1,0,0,1,1,0,3,"-25,30335724","-48,94378885",True
12,331925.0,2021-01-01,sexta-feira,20:30:00,BA,116,709,MANOEL VITORINO,Demais falhas mecânicas ou elétricas,Incêndio,...,0,0,0,1,1,0,2,"-14,10719019","-40,22427462",True
13,331952.0,2021-01-02,sábado,05:00:00,PE,424,"3,1",ARCOVERDE,Transitar na contramão,Colisão lateral,...,0,0,1,1,0,1,2,"-8,45381694","-37,0485949",False
14,331957.0,2021-01-02,sábado,06:15:00,MG,381,"601,7",CARMOPOLIS DE MINAS,Condutor Dormindo,Saída de leito carroçável,...,0,1,0,0,0,1,1,"-20,63243704","-44,73521221",False

In [92]:
#Criar coluna "acidente_fatal" (variável-alvo para futuro projeto de ML)

df['acidente_fatal'] = np.where(df['mortos'] > 0, 1,0)
df['acidente_fatal'].value_counts()

acidente_fatal
0    318000
1     24619
Name: count, dtype: int64

In [93]:
df['latitude'] = df['latitude'].str.replace(',', '.').astype(float)
df['longitude'] = df['longitude'].str.replace(',', '.').astype(float)

In [94]:
df.to_csv('../dados/dados_tratados/prf_tratado.csv', index=False)